# Generated by Django 6.0.6 on 2026-08-04 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreachAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("domain", models.CharField(blank=True, default="", max_length=200)),
                ("breach_date", models.DateField(blank=True, null=True)),
                ("added_date", models.DateField(blank=True, null=True)),
                ("pwn_count", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("data_classes", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-breach_date"],
            },
        ),
        migrations.CreateModel(
            name="ScamRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("weight", models.PositiveSmallIntegerField(default=10)),
                (
                    "pattern",
                    models.TextField(
                        help_text="Python regex pattern (case-insensitive)"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed (hardcoded original)"),
                            ("admin", "Admin (manually added)"),
                            ("ai", "AI-generated"),
                        ],
                        default="admin",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-weight", "code"],
            },
        ),
        migrations.CreateModel(
            name="ScamShortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("admin", "Admin"),
                            ("auto", "Auto-fetched"),
                        ],
                        default="admin",
                        max_length=10,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="ScamUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("rules_added", models.PositiveIntegerField(default=0)),
                ("rules_updated", models.PositiveIntegerField(default=0)),
                ("shorteners_added", models.PositiveIntegerField(default=0)),
                ("source", models.CharField(default="ai", max_length=20)),
                ("details", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
    ]
