"""
Django settings for core_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# All three of these are env-driven so a VPS deploy is a .env edit, never a
# code edit. The defaults are the local-development values, so nothing about
# running this on the dev box changes.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY"
) or "django-insecure-w%dot3@qs@n^wzrs85t^&31u(8f-#q6g129h55jikv^nhizwbq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Comma-separated in the env, e.g. "coreripper.com,www.coreripper.com".
# With DEBUG on, Django already implies localhost/127.0.0.1, so the empty
# default keeps local development working exactly as before; with DEBUG off it
# must be set or every request 400s (DisallowedHost).
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# Django requires the scheme here for any cross-origin POST (the Lenco webhook
# arrives server-to-server so it's unaffected, but the frontend's own calls are
# not). Same comma-separated shape, e.g. "https://coreripper.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Cookie security (Part A8 of the monetization plan  Free tier shows ads, so
# a real consent flow needs real cookie hardening behind it). SECURE is tied
# to DEBUG rather than hardcoded True: the dev server runs on plain HTTP, and
# a browser silently drops a Secure cookie set over HTTP  hardcoding True
# here would break session/CSRF cookies (and Django admin login) locally.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "network_tools.apps.NetworkToolsConfig",
    "accounts",
    "core",
    "payments",
    "blog",
    "dashboard",
    "django_celery_beat",
    "monitors",
    "news",
    "hardware",
    "credits",
]

SITE_ID = 1

MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.TokenAuthMiddleware",
    "core.middleware.FeatureFlagMiddleware",  # after TokenAuth: needs request.user for the superuser bypass
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "corelom"),
        "USER": os.environ.get("DB_USER", "corelom"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "corelom_dev_pw"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        # Without this, Django opens a fresh TCP connection + auth handshake
        # to Postgres on every single request, and this frontend fires many
        # small API calls per page load (stats, entitlements, credits, tool
        # lists...) - that overhead compounds into real, site-wide latency.
        # Keeps a connection alive per worker process for up to 60s instead
        # of reconnecting every time; CONN_HEALTH_CHECKS pings it before
        # reuse so a connection Postgres already closed doesn't get handed
        # to a request and fail.
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": True,
    }
}


# Cache
# Used by core/llm.py to avoid re-hitting the paid LLM API for identical prompts,
# and by accounts/trial.py + core/quota.py for the guest trial / free daily quota
# counters. LocMemCache is per-process and doesn't survive a restart or share
# state across multiple workers.
#
# Swapped to RedisCache on 2026-07-16 once `redis-cli ping` returned PONG
# and redis-server was confirmed running as a live service (see
# MONITORING_SETUP_COMMANDS.md §1-2). db 2 here is distinct from Celery's
# broker/backend (db 0/1) below.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/2",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

# --- Celery (monitors app) ---
# Broker/backend point at Redis db 0/1 (db 2 is the CACHES entry above).
# redis-server is installed and enabled as a systemd unit on this box, so these
# work from boot; MONITORING_SETUP_COMMANDS.md covers that privileged setup.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_TIME_LIMIT = 120  # hard kill any task running over 2 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 90

# --- WhatsApp alert sender (monitors app) ---
# The Octavian bot's localhost-only internal send API (see monitors/whatsapp.py).
# It's a separate Node process holding a live WhatsApp Web session, so it may not
# be on this host once CoreRipper moves to a VPS  hence a setting, not a literal.
WHATSAPP_BOT_URL = os.environ.get("WHATSAPP_BOT_URL", "http://127.0.0.1:3001")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Only consulted by `collectstatic` (i.e. only matters in production behind
# nginx  DEBUG=1's runserver serves admin/static assets itself and ignores
# this). No effect on local dev.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Support ticket attachments (accounts.SupportTicketAttachment)  the only
# user-uploaded files in this project so far.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# CORS. The frontend is static HTML served from a *different* origin in dev
# (127.0.0.1:5501 vs the API on :8000), so development needs allow-all; once
# deployed the frontend is same-origin and CORS is only needed for whatever
# extra origins you name. Comma-separated, scheme included, e.g.
# "https://coreripper.com,https://www.coreripper.com".
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()
]
# Allow-all is *only* the DEBUG-and-unconfigured case, so a production deploy
# can never silently stay wide open: with DEBUG=0 and no whitelist, cross-origin
# calls fail loudly (visible CORS error) rather than being quietly accepted.
# On this box DEBUG defaults to 1, so local behavior is unchanged.
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS

# --- Outgoing email ---
# Three transports, picked automatically in this order:
#   1. Resend (production): paste RESEND_API_KEY. Mail leaves over
#      smtp.resend.com:465 (SSL) authenticated as the literal user "resend"
#      with the API key as the password, sending as the coreripper.site
#      addresses below (the domain's DKIM is authorised in Resend, and
#      Cloudflare Email Routing forwards replies to those addresses back to
#      the Gmail inbox).
#   2. Gmail (legacy/dev): EMAIL + PASSKEY (a 16-char Gmail App Password, not
#      the account password). Gmail only honours a From: that is a verified
#      "Send mail as" alias on that account  otherwise it silently rewrites
#      the header to the authenticated address.
#   3. Neither configured: Django's console backend, so the signup/reset flows
#      stay fully testable locally (the code just prints to the runserver log).
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
GMAIL_ADDRESS = os.environ.get("EMAIL", "")
GMAIL_APP_PASSWORD = os.environ.get("PASSKEY", "")

# One sender per purpose, so a user can tell an outage alert from an invoice at
# a glance and can reply to the right inbox. Call sites pass these explicitly
# never fall back to DEFAULT_FROM_EMAIL for mail that has an obvious owner.
EMAIL_DOMAIN = os.environ.get("EMAIL_DOMAIN", "coreripper.site")
EMAIL_FROM_SECURITY = os.environ.get(
    "EMAIL_FROM_SECURITY", f"CoreRipper Security <security@{EMAIL_DOMAIN}>"
)  # signup verification, password reset  anything account-credential shaped
EMAIL_FROM_BILLING = os.environ.get(
    "EMAIL_FROM_BILLING", f"CoreRipper Billing <billing@{EMAIL_DOMAIN}>"
)  # receipts, renewal notices  anything money-shaped
EMAIL_FROM_ALERTS = os.environ.get(
    "EMAIL_FROM_ALERTS", f"CoreRipper Alerts <alert@{EMAIL_DOMAIN}>"
)  # monitor alerts, plus the automated digests/newsletters (no reply expected)
EMAIL_FROM_SUPPORT = os.environ.get(
    "EMAIL_FROM_SUPPORT", f"CoreRipper Support <support@{EMAIL_DOMAIN}>"
)  # support tickets and their acknowledgements  a human reads the replies

# Support is the safest default for anything not explicitly routed: a stray
# reply reaches a monitored inbox rather than a black hole.
DEFAULT_FROM_EMAIL = EMAIL_FROM_SUPPORT
SERVER_EMAIL = EMAIL_FROM_ALERTS  # Django's own error mail

if RESEND_API_KEY:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.resend.com"
    EMAIL_PORT = 465
    EMAIL_USE_SSL = True
    EMAIL_HOST_USER = "resend"
    EMAIL_HOST_PASSWORD = RESEND_API_KEY
elif GMAIL_ADDRESS and GMAIL_APP_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = GMAIL_ADDRESS
    EMAIL_HOST_PASSWORD = GMAIL_APP_PASSWORD
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""

# Django's SMTP backend has no timeout by default, so a blocked/unreachable
# outbound port (common on fresh VPS instances until the provider allows
# 465/587) hangs the request indefinitely instead of failing fast. Every
# send_mail() call in the codebase is synchronous and on the request thread
# (signup, password reset, receipts, alerts), so one stuck connection can
# make the whole site feel unresponsive, not just the email-triggering
# endpoint. Bounded here so a real outage surfaces as a fast, catchable
# error instead of a hang.
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
# --- News feed aggregator (news app) ---
# Base URL used to build the "review this draft" link in the digest email.
# No production domain is configured yet, so this defaults to the local dev
# backend  update via env once CoreRipper is actually deployed.
SITE_URL = os.environ.get("SITE_URL", "http://127.0.0.1:8000")

# Base URL for the static frontend (a different origin/port than SITE_URL in
# dev  the frontend has no build step and is served separately, e.g. VS
# Code Live Server at 127.0.0.1:5500/frontend). Used to build article links
# in the newsletter email (accounts/tasks.py::send_newsletter).
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://127.0.0.1:5500/frontend")

# Who gets the "N drafts ready for review" digest. Defaults to the alert inbox
# (Cloudflare Email Routing forwards it to the real Gmail), falling back to the
# raw Gmail address on a box with no domain configured  set
# NEWS_FEED_REVIEWER_EMAIL to route it elsewhere without touching code.
NEWS_FEED_REVIEWER_EMAIL = os.environ.get(
    "NEWS_FEED_REVIEWER_EMAIL", f"alert@{EMAIL_DOMAIN}" or GMAIL_ADDRESS
)

# Where support-ticket submissions are delivered (accounts.views.support_ticket_view).
# This is a *destination*, not a sender: the bare support@ mailbox, which
# Cloudflare forwards to the Gmail inbox where a human answers it.
SUPPORT_EMAIL = os.environ.get("SUPPORT_EMAIL", f"support@{EMAIL_DOMAIN}")

NEWS_FEED_TRENDING_THRESHOLD = int(os.environ.get("NEWS_FEED_TRENDING_THRESHOLD", "50"))
NEWS_FEED_MAX_DRAFTS_PER_RUN = int(os.environ.get("NEWS_FEED_MAX_DRAFTS_PER_RUN", "5"))

# --- Intelligent content engine (core/intel) ---
# Dedicated Gemini key for the article-analysis + image pipeline and the
# auto-editor. Kept separate from the customer-facing LLM_FALLBACK_* Gemini
# config on purpose: internal editorial work must never touch the credit wallet
# or share the AI budget. Unset => the pipeline degrades to a best-effort search
# from the raw title (never crashes). See core/intel/gemini.py.
INTEL_GEMINI_API_KEY = os.environ.get("INTEL_gen_news_gemini", "")
INTEL_GEMINI_BASE_URL = os.environ.get(
    "INTEL_GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta/openai/"
)
INTEL_GEMINI_MODEL = os.environ.get("INTEL_GEMINI_MODEL", "gemini-flash-latest")

# Google Custom Search (image) provider. Needs BOTH a key and a Programmable
# Search Engine id (cx). Key defaults to the INTEL Gemini key above; cx must be
# supplied to enable web image search. With no cx, the pipeline falls back to
# Wikimedia Commons automatically. See core/intel/image_search.py.
GOOGLE_IMAGE_SEARCH_KEY = os.environ.get("GOOGLE_IMAGE_SEARCH_KEY", "") or INTEL_GEMINI_API_KEY
GOOGLE_CSE_ID = os.environ.get("GOOGLE_CSE_ID", "")

# Minimum heuristic confidence (0-1) for a resolved image to be stored; below
# this the article keeps the per-category fallback. See core/intel/pipeline.py.
INTEL_IMAGE_CONFIDENCE_THRESHOLD = float(os.environ.get("INTEL_IMAGE_CONFIDENCE_THRESHOLD", "0.60"))

# Auto-editor: how many days a published article may go un-refreshed before the
# scheduled pass reconsiders it, and how many to process per run (cost guard).
INTEL_AUTOEDIT_MIN_AGE_DAYS = int(os.environ.get("INTEL_AUTOEDIT_MIN_AGE_DAYS", "7"))
INTEL_AUTOEDIT_MAX_PER_RUN = int(os.environ.get("INTEL_AUTOEDIT_MAX_PER_RUN", "10"))

# --- Credits / AI metering (credits app  Phase 1 monetization) ---
# The whole economic engine lives in these constants. Credits meter Claude
# token consumption only; Groq/Gemini stay free (governed by core/quota.py's
# $-spend guardrails instead). TOKENS_PER_CREDIT is the only tuning lever 
# customer-facing prices never move.
TOKENS_PER_CREDIT = 250  # 1 credit = 250 Claude tokens (input + output)
MIN_CREDIT_CHARGE = 1  # every Claude call charges at least 1 credit
CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "claude-sonnet-5")  # config only; NEVER rendered in customer copy
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_BASE_URL = os.environ.get("ANTHROPIC_BASE_URL", "https://api.anthropic.com")

# Monthly subscription-credit grant per plan tier (reset on renewal/settlement).
TIER_MONTHLY_CREDITS = {"free": 0, "lite": 250, "standard": 700, "pro": 1500}

TRIAL_DAYS = 3  # every verified signup: 3 days of pro-tier features, zero credits
RENEWAL_NOTICE_DAYS = 2  # T-2 days: renewal_state -> awaiting_payment + nudge email
RENEWAL_GRACE_DAYS = 3  # past period end: grace window before expiry to free
PACK_CREDIT_LIFETIME_DAYS = 365  # pack ("boost") credits expire 12 months after purchase
CREDIT_LOW_BALANCE_THRESHOLD = 25  # header widget switches to its "low" (amber) state below this

# Session lifetimes (session-hardening pass, 2026-07-25). Access tokens now
# expire; "Remember Me" at login issues a rotating refresh token
# (accounts.RefreshToken) that silently renews them. Without it, a login
# simply lapses after AUTH_TOKEN_LIFETIME_HOURS.
AUTH_TOKEN_LIFETIME_HOURS = int(os.environ.get("AUTH_TOKEN_LIFETIME_HOURS", "8"))
REFRESH_TOKEN_LIFETIME_DAYS = int(os.environ.get("REFRESH_TOKEN_LIFETIME_DAYS", "60"))

# Temporary kill switch: Lenco card payments stay wired but hidden until
# explicitly re-enabled (user decision  mobile money only for now).
PAYMENTS_CARD_ENABLED = os.environ.get("PAYMENTS_CARD_ENABLED", "0") == "1"

# Hard per-operation output caps for every AI call (cost control  never an
# uncapped call). The first block are the 7 operations wired today and keep
# their pre-credits per-call values; the second block pre-seeds the planned
# AI enrichments from the monetization doc so wiring them later is config-only.
MAX_OUTPUT_TOKENS = {
    "feedback_tutor": 800,
    "quiz_generator": 1200,
    "coding_helper": 800,
    "dashboard_fix": 400,
    "dashboard_report": 700,
    "dashboard_assistant": 400,
    "news_draft": 700,
    "news_wrapup": 400,
    "dns_analysis": 600,
    "ssl_check": 600,
    "subnet_lookup": 400,
    "crawler_scan": 800,
    "regex_builder": 700,
    "security_report_basic": 1200,
    "security_report_detailed": 2500,
    "security_report_advanced": 4000,
    "generate_fix": 2000,
    "verify_fix": 800,
    "email_wizard": 1500,
    "code_review": 3000,
    "hardware_verdict": 300,
    "hardware_knowledge": 700,
    "scam_pattern_update": 1200,
    "default": 800,
}

# Django's own default logging only reports 500s via mail_admins() when
# DEBUG=False, which silently no-ops with an empty ADMINS list (the
# out-of-the-box state here) - production exceptions vanish instead of
# reaching anywhere. This routes django.request (and everything else) to
# stderr instead, which gunicorn's --error-logfile already captures, so a
# real traceback shows up in ops logs rather than nowhere.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
