# Generated by Django 6.0.6 on 2026-07-16 13:05

from django.db import migrations


def create_periodic_task(apps, schema_editor):
    """Registers accounts.tasks.send_weekly_digests to run every Monday at
    08:00 UTC, via django-celery-beat's DB-backed schedule  same pattern as
    monitors/migrations/0002_register_dispatch_periodic_task.py. Only takes
    effect once celery beat is actually running."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="8", day_of_week="1", day_of_month="*", month_of_year="*",
    )
    PeriodicTask.objects.get_or_create(
        name="Send weekly digest emails",
        defaults={
            "crontab": schedule,
            "task": "accounts.tasks.send_weekly_digests",
        },
    )


def remove_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="Send weekly digest emails").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_backfill_profile_notification_prefs"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_periodic_task, remove_periodic_task),
    ]
