# Generated by Django 6.0.6 on 2026-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_fxrate_remove_planprice_amount_zmw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planprice",
            name="plan",
            field=models.CharField(
                choices=[
                    ("lite", "Lite"),
                    ("standard", "Standard"),
                    ("pro", "Pro"),
                    ("premium", "Premium (legacy)"),
                ],
                default="pro",
                max_length=20,
            ),
        ),
    ]
