# Generated by Django 6.0.6 on 2026-07-24 09:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_balance", models.PositiveIntegerField(default=0)),
                ("pack_balance", models.PositiveIntegerField(default=0)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=64)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("gemini", "Gemini"),
                            ("claude", "Claude"),
                        ],
                        max_length=16,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=64)),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                (
                    "est_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("credits_charged", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="credits_aiu_user_id_32a7ba_idx",
                    ),
                    models.Index(
                        fields=["operation", "created_at"],
                        name="credits_aiu_operati_1624a1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "bucket",
                    models.CharField(
                        choices=[("subscription", "Subscription"), ("pack", "Pack")],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("monthly_refresh", "Monthly refresh"),
                            ("pack_purchase", "Pack purchase"),
                            ("spend", "Spend"),
                            ("expiry_reset", "Expiry reset"),
                            ("pack_expiry", "Pack expiry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation", models.CharField(blank=True, max_length=64)),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("balance_after", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="credits_cre_user_id_a63878_idx",
                    ),
                    models.Index(
                        fields=["user", "bucket"], name="credits_cre_user_id_f332f3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PackCreditLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_granted", models.PositiveIntegerField()),
                ("credits_remaining", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("purchase_ref", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_credit_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_lots",
                        to="credits.creditwallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="credits_pac_user_id_48db4d_idx",
                    )
                ],
            },
        ),
    ]
