# Generated by Django 6.0.6 on 2026-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_register_weekly_wrapup_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsdraft",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped once by the weekly wrap-up (news.tasks.news_weekly_wrapup). An archived article keeps its own detail page (SEO-indexable, never deleted) but drops off the main feed/related-articles surfaces.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleupdate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("update", "Content Update"),
                    ("correction", "Correction"),
                    ("advisory", "Advisory / Release Note"),
                    ("archived", "Archived"),
                ],
                default="update",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsdraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
