# Generated by Django 6.0.6 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="tier",
            field=models.CharField(
                choices=[
                    ("local", "Local (free-tier eligible)"),
                    ("api", "API (Premium only)"),
                ],
                default="local",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="tool_key",
            field=models.CharField(
                blank=True,
                help_text="Backend dispatch key used in /api/toolbox/?tool=… . Blank for frontend-only tools.",
                max_length=50,
            ),
        ),
    ]
