# Generated by Django 6.0.6 on 2026-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_feature_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[("news", "News"), ("hardware", "Hardware")],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("image_url", models.URLField(max_length=500)),
                ("thumb_url", models.URLField(max_length=500)),
                ("credit_name", models.CharField(blank=True, max_length=255)),
                ("credit_url", models.URLField(blank=True, max_length=500)),
                ("license_name", models.CharField(blank=True, max_length=100)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["app", "category", "id"],
                "unique_together": {("app", "category", "image_url")},
            },
        ),
    ]
