# Generated by Django 6.0.6 on 2026-07-16 12:35

from django.db import migrations


def backfill(apps, schema_editor):
    """The Profile/NotificationPreference auto-create signal only fires on
    User creation, so every user that existed before this migration needs a
    row created here  otherwise request.user.profile throws for them."""
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    NotificationPreference = apps.get_model("accounts", "NotificationPreference")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)
        NotificationPreference.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_notificationpreference_profile_supportticket_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
