# Generated by Django 6.0.6 on 2026-07-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_register_newsletter_periodic_task"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="period_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="payment",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.planprice",
            ),
        ),
    ]
