# Generated by Django 6.0.6 on 2026-07-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_payment_activated_at_payment_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cookie_consent_version",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_model",
            field=models.CharField(
                choices=[("groq", "Groq"), ("gemini", "Gemini"), ("claude", "Claude")],
                default="groq",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="renewal_state",
            field=models.CharField(
                choices=[
                    ("not_due", "Not due"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("grace", "Grace"),
                ],
                default="not_due",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="expired",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("lite", "Lite"),
                    ("standard", "Standard"),
                    ("pro", "Pro"),
                    ("premium", "Premium (legacy)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
