# Generated by Django 6.0.6 on 2026-07-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_map_active_to_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="active",
        ),
    ]
