# Generated by Django 6.0.6 on 2026-07-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_subscription_active"),
        ("payments", "0005_creditpackprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="credits_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.creditpackprice",
            ),
        ),
    ]
