# Generated by Django 6.0.6 on 2026-07-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=80)),
                ('generation', models.CharField(blank=True, max_length=80)),
                ('architecture', models.CharField(blank=True, max_length=80)),
                ('socket', models.CharField(blank=True, max_length=50)),
                ('cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('threads', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cache_mb', models.FloatField(blank=True, help_text='Total cache, MB', null=True)),
                ('base_clock_ghz', models.FloatField(blank=True, null=True)),
                ('boost_clock_ghz', models.FloatField(blank=True, null=True)),
                ('tdp_watts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('process_node_nm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=80)),
                ('vram_gb', models.FloatField(blank=True, null=True)),
                ('cuda_or_stream_cores', models.PositiveIntegerField(blank=True, help_text='CUDA cores (NVIDIA) or Stream Processors (AMD)', null=True)),
                ('ray_tracing', models.BooleanField(default=False)),
                ('power_draw_watts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_psu_watts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_outputs', models.CharField(blank=True, help_text="e.g. '3x DisplayPort 2.1, 1x HDMI 2.1'", max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MobileSoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=80)),
                ('cpu_architecture', models.CharField(blank=True, max_length=150)),
                ('gpu', models.CharField(blank=True, help_text="Integrated GPU name, e.g. 'Adreno 750'", max_length=150)),
                ('ai_engine', models.CharField(blank=True, help_text="e.g. 'Hexagon NPU'", max_length=150)),
                ('fabrication_process_nm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supported_phones', models.TextField(blank=True, help_text='Comma-separated or freeform list of known phones')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile SoC',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('cpus', 'CPUs'), ('gpus', 'GPUs'), ('gaming', 'Gaming'), ('gaming_laptops', 'Gaming Laptops'), ('desktop_pcs', 'Desktop PCs'), ('smartphones', 'Smartphones'), ('mobile_socs', 'Mobile SoCs'), ('monitors', 'Monitors'), ('storage', 'Storage (SSD/HDD)'), ('ram', 'RAM'), ('motherboards', 'Motherboards'), ('cooling', 'Cooling'), ('pc_building', 'PC Building'), ('buying_guides', 'Hardware Buying Guides')], max_length=30)),
                ('ai_summary', models.TextField(blank=True, help_text='Short blurb for card previews / digests')),
                ('ai_draft_body', models.TextField(blank=True, help_text='Full article body')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='hardware.cpu')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='hardware.gpu')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='hardware.hardwarearticle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HardwareArticleUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('published', 'Published'), ('update', 'Content Update'), ('correction', 'Correction'), ('advisory', 'Advisory / Release Note')], default='update', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='hardware.hardwarearticle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=80)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('display', models.CharField(blank=True, help_text='e.g. \'16" 2560x1600 OLED\'', max_length=150)),
                ('refresh_rate_hz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_whr', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='hardware.cpu')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='hardware.gpu')),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hardwarearticle',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='hardware.laptop'),
        ),
        migrations.AddField(
            model_name='hardwarearticle',
            name='mobile_soc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='hardware.mobilesoc'),
        ),
    ]
