# Generated by Django 6.0.6 on 2026-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_register_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSpecChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('laptop', 'Laptop'), ('mobile_soc', 'Mobile SoC')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=60)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='cpu',
            name='efficiency_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='value_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='value_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='portability_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='value_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='mobilesoc',
            name='efficiency_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.AddField(
            model_name='mobilesoc',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mobilesoc',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilesoc',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CoreRipper curated 0-100 score, not provider-sourced', null=True),
        ),
        migrations.CreateModel(
            name='HardwareAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('laptop', 'Laptop'), ('mobile_soc', 'Mobile SoC')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('best_for', models.JSONField(blank=True, default=list, help_text='e.g. ["Students", "Programming", "Office"]')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('trade_offs', models.JSONField(blank=True, default=list)),
                ('expected_lifespan_years', models.CharField(blank=True, help_text="e.g. '5+ years'", max_length=20)),
                ('recommended_ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_ssd_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict_text', models.TextField(blank=True, help_text='Short prose summary shown on device pages')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='published', max_length=20)),
                ('source_spec_hash', models.CharField(blank=True, help_text='sha256 of the tracked spec fields this profile was generated from', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('type_key', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='HardwareComparisonVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('laptop', 'Laptop'), ('mobile_soc', 'Mobile SoC')], max_length=20)),
                ('id_a', models.PositiveIntegerField()),
                ('id_b', models.PositiveIntegerField()),
                ('verdict', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type_key', 'id_a', 'id_b')},
            },
        ),
        migrations.CreateModel(
            name='HardwareDeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('laptop', 'Laptop'), ('mobile_soc', 'Mobile SoC')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('image_type', models.CharField(choices=[('main', 'Main'), ('gallery', 'Gallery'), ('front', 'Front'), ('back', 'Back'), ('side', 'Side'), ('keyboard', 'Keyboard'), ('ports', 'Ports'), ('motherboard', 'Motherboard'), ('packaging', 'Packaging'), ('thumbnail', 'Thumbnail'), ('logo', 'Manufacturer Logo')], default='main', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('source_name', models.CharField(blank=True, help_text="e.g. 'Wikimedia Commons'", max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('license_name', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, help_text="e.g. '1920x1080'", max_length=20)),
                ('content_hash', models.CharField(db_index=True, help_text='sha256 of the URL  dedupe key, prevents re-syncing the same image twice', max_length=64)),
                ('credit_name', models.CharField(blank=True, max_length=150)),
                ('credit_url', models.URLField(blank=True, max_length=500)),
                ('is_admin_override', models.BooleanField(default=False, help_text='True for an admin-uploaded image; always wins over a provider-sourced one of the same image_type')),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type_key', 'object_id', 'image_type'],
                'unique_together': {('type_key', 'object_id', 'content_hash')},
            },
        ),
        migrations.CreateModel(
            name='HardwareFieldSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('laptop', 'Laptop'), ('mobile_soc', 'Mobile SoC')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=60)),
                ('provider_key', models.CharField(max_length=40)),
                ('raw_value', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type_key', 'object_id', 'field_name'],
                'unique_together': {('type_key', 'object_id', 'field_name')},
            },
        ),
    ]
