# Generated by Django 6.0.6 on 2026-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_register_spec_sync_periodic_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareaiprofile',
            name='expected_lifespan_years',
            field=models.CharField(blank=True, help_text="e.g. '5+ years'", max_length=60),
        ),
    ]
