# Generated by Django 6.0.6 on 2026-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_hardwareaiprofile_expected_lifespan_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaredeviceimage',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
