# Generated by Django 6.0.6 on 2026-07-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0009_reschedule_auto_edit_monthly"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HardwareComparisonVerdict",
        ),
    ]
