# Generated by Django 6.0.6 on 2026-07-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_seed_categories_and_site"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminAuthToken",
        ),
    ]
