# Generated by Django 6.0.6 on 2026-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_adminauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional. Falls back to a category icon if blank.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author_name",
            field=models.CharField(default="CoreRipper Team", max_length=80),
        ),
    ]
