# Generated by Django 6.0.6 on 2026-07-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_cover_image_url_alter_post_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="auto_managed",
            field=models.BooleanField(
                default=False,
                help_text="If set, the auto-editor may refresh this post's body text, not just its image/SEO.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_credit",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_credit_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_license",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_provider",
            field=models.CharField(
                blank=True, help_text="google | commons", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_query",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_source",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Wikimedia Commons' or a domain",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_last_edited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the auto-editor last ran a real refresh",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_source_hash",
            field=models.CharField(
                blank=True,
                help_text="Change-gate: unchanged => scheduled refresh is a no-op",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intel_thumb_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
