# Generated by Django 6.0.6 on 2026-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reschedule_auto_edit_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intel_image_locked',
            field=models.BooleanField(default=False, help_text='When True, the auto-editor will not replace this image. Set automatically when an admin manually selects an image via the cockpit.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intel_image_provider',
            field=models.CharField(blank=True, help_text='google | commons | manual', max_length=20),
        ),
    ]
