# Generated by Django 6.0.6 on 2026-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "plan",
                    models.CharField(
                        choices=[("premium", "Premium")],
                        default="premium",
                        max_length=20,
                    ),
                ),
                (
                    "display_amount_usd",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("amount_zmw", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
