# Generated by Django 6.0.6 on 2026-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_default_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=7, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='planprice',
            name='amount_zmw',
        ),
    ]
