# Generated by Django 6.0.6 on 2026-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_planprice_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("credits", models.PositiveIntegerField()),
                (
                    "display_amount_usd",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
