# Generated by Django 6.0.6 on 2026-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dev-tools", "Developer Tools"),
                            ("ai-tools", "AI Tools"),
                            ("network-tools", "Network Tools"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Path relative to frontend/, e.g. dev-tools/json_formatter.html",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin-only notes, e.g. what's currently wrong",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
