# Generated by Django 6.0.6 on 2026-07-15 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tool_tier_tool_tool_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubnetDrillStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak_days", models.IntegerField(default=0)),
                ("longest_streak_days", models.IntegerField(default=0)),
                ("last_practiced_date", models.DateField(blank=True, null=True)),
                ("total_problems_solved", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnet_drill_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
