# Generated by Django 6.0.6 on 2026-07-14 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_key",
                    models.CharField(
                        choices=[
                            ("ssl_info", "SSL Certificate Checker"),
                            ("ssl_expiration", "SSL Expiration Checker"),
                            ("ping", "Ping Tool"),
                            ("http_status", "HTTP Status Checker"),
                            ("dns", "DNS Lookup"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                (
                    "check_interval_minutes",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (60, "1 hour"),
                            (360, "6 hours"),
                            (1440, "24 hours"),
                        ],
                        default=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("alert", "Alert"),
                            ("pending", "Pending first check"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_json", models.JSONField(blank=True, null=True)),
                ("alert_email", models.BooleanField(default=True)),
                ("alert_whatsapp", models.BooleanField(default=False)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("change_summary", models.TextField()),
                ("previous_status", models.CharField(max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                ("sent_email", models.BooleanField(default=False)),
                ("sent_whatsapp", models.BooleanField(default=False)),
                ("seen_by_user", models.BooleanField(default=False)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitors.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="monitor",
            constraint=models.UniqueConstraint(
                fields=("user", "tool_key", "target"),
                name="uniq_monitor_per_user_tool_target",
            ),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["monitor", "triggered_at"],
                name="monitors_al_monitor_9fa24d_idx",
            ),
        ),
    ]
