# Generated by Django 6.0.6 on 2026-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0002_register_dispatch_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="check_interval_minutes",
            field=models.IntegerField(
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (60, "1 hour"),
                    (360, "6 hours"),
                    (1440, "24 hours"),
                    (10080, "Weekly"),
                ],
                default=60,
            ),
        ),
    ]
