# Generated by Django 6.0.6 on 2026-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0003_alter_monitor_check_interval_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertlog",
            name="whatsapp_error",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
